budget/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from budget.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('units/', include('units.urls')),
    path('contacts/', include('contacts.urls')),
    path('items/', include('items.urls')),
    path('transactions/', include('transactions.urls')),
    path('accounts/', include('accounts.urls')),
    path('brands/', include('brands.urls')),
    path('', IndexView.as_view(), name="home"),
]

items/urls.py
from django.urls import path

from . import views

app_name = 'items'
urlpatterns = [
    path('', views.ItemListView.as_view(), name='index'),
    path('<int:pk>/', views.ItemDetailView.as_view(), name='detail'),
    path('create/', views.create_item, name='create'),
    path('<int:pk>/edit/', views.ItemUpdateView.as_view(), name='edit'),
    path('generic/', views.GenericItemListView.as_view(), name='generic-index'),
    path('generic/<int:pk>/', views.GenericItemDetailView.as_view(), name='generic-detail'),
    path('generic/create/', views.create_generic_item, name='generic-create'),
    path('generic/<int:pk>/edit/', views.GenericItemUpdateView.as_view(), name='generic-edit'),
]

transactions/urls.py
from django.urls import path

from . import views

app_name = 'transactions'
urlpatterns = [
    path('', views.TransactionListView.as_view(), name='index'),
    path('<int:pk>/', views.TransactionDetailView.as_view(), name='detail'),
    path('create/', views.create_transaction, name='create'),
    path('<int:pk>/edit/', views.TransactionUpdateView.as_view(), name='edit'),
    path('manage/', views.manage_transactions, name='manage'),
    path('detail/', views.TransactionDetailListView.as_view(), name='detail-index'),
    path('detail/<int:pk>/', views.TransactionDetailDetailView.as_view(), name='detail-detail'),
    path('detail/create/', views.create_transaction_detail, name='detail-create'),
    path('detail/<int:pk>/edit/', views.TransactionDetailUpdateView.as_view(), name='detail-edit'),
]

transactions/models.py
import datetime
from django.db import models
from django.db.models import Avg, Count, Min, Sum, Max, F
from django.urls import reverse
from decimal import *

class Transaction(models.Model):
    date = models.DateTimeField('Date')
    #card_used = models.ForeignKey('accounts.card_number_last4', on_delete=SET_NULL, verbose_name="card used")
    total_custom = models.DecimalField('Custom Total', max_digits=10, decimal_places=2, default=0)
    tax_total_custom = models.DecimalField('Custom Tax Total', max_digits=10, decimal_places=2, default=0)
    tip_total = models.DecimalField('Tip Total', max_digits=10, decimal_places=2, default=0)
    bags_total = models.DecimalField('Bags Total', max_digits=10, decimal_places=2, default=0)
    donation_total = models.DecimalField('Donation Total', max_digits=10, decimal_places=2, default=0)
    grand_total_custom = models.DecimalField('Custom Grand Total', max_digits=10, decimal_places=2, default=0)
    contact_custom = models.ForeignKey('contacts.Contact', null=True, blank=True, on_delete=models.SET_NULL, verbose_name="custom contact", related_name='transaction_as_contact_custom_set')
    account_from = models.ForeignKey('accounts.Account', null=True, blank=True, on_delete=models.SET_NULL, verbose_name="from account", related_name='transaction_as_account_from_set')
    account_to = models.ForeignKey('accounts.Account', null=True, blank=True, on_delete=models.SET_NULL, verbose_name="to account", related_name='transaction_as_account_to_set')
    address = models.ForeignKey('contacts.Address', null=True, blank=True, on_delete=models.SET_NULL, related_name='transaction_as_address_set', verbose_name="address")

    @property
    def total_from_transactiondetail(self):
        price_final_total = Transaction.objects.annotate(total=Sum('transactiondetail_as_transaction_set__quantity'))
        return price_final_total[0].total

    def get_absolute_url(self):
        return reverse('transactions:detail', kwargs={'pk': self.pk})

    def __str__(self):
        if self.date:
            return str(self.date)
        else:
            return "Transaction"

class TransactionDetail(models.Model):
    quantity = models.DecimalField('Quantity', max_digits=10, decimal_places=5, default=1)
    price_regular_custom = models.DecimalField('Custom Regular Price', max_digits=10, decimal_places=5, default=0)
    discount_custom = models.DecimalField('Custom Discount', max_digits=10, decimal_places=5, default=0)
    price_discounted_custom = models.DecimalField('Custom Discounted Price', max_digits=10, decimal_places=5, default=0)
    price_extended_custom = models.DecimalField('Custom Extended Price', max_digits=10, decimal_places=5, default=0)
    crv_per_custom = models.DecimalField('Custom CRV Per', max_digits=10, decimal_places=5, default=0)
    tax_per_custom = models.DecimalField('Custom Tax Per', max_digits=10, decimal_places=5, default=0)
    transaction = models.ForeignKey('Transaction', null=True, on_delete=models.SET_NULL, related_name='transactiondetail_as_transaction_set', verbose_name="transaction")
    item = models.ForeignKey('items.Item', blank=True, null=True, on_delete=models.SET_NULL, related_name='transactiondetail_as_item_set')
    generic_item = models.ForeignKey('items.GenericItem', blank=True, null=True, on_delete=models.SET_NULL, related_name='transactiondetail_as_generic_item_set', verbose_name="generic item")
    base_unit_custom = models.ForeignKey('units.Unit', blank=True, null=True, on_delete=models.SET_NULL, related_name="transactiondetail_as_base_unit_custom_set", verbose_name="custom base unit")
    unit_factor_custom = models.DecimalField('Custom Unit Factor', max_digits=10, decimal_places=5, blank=True, null=True)

    @property
    def price_discounted_calculated(self):
        if self.price_regular_custom and self.discount_custom:
            return round(self.price_regular_custom - self.discount_custom, 5)
        else:
            return

    @property
    def discount_calculated(self):
        if self.price_regular_custom and self.price_discounted_custom:
            return round(self.price_regular_custom - self.price_discounted_custom, 5)
        else:
            return

    @property
    def price_regular_calculated(self):
        if self.price_discounted_custom and self.discount_custom:
            return round(self.price_discounted_custom + self.discount_custom, 5)
        else:
            return

    @property
    def price_final(self):
        if self.price_discounted_custom:
            return self.price_discounted_custom
        elif self.price_discounted_calculated:
            return self.price_discounted_calculated
        elif self.price_regular_custom:
            return self.price_regular_custom
        else:
            return

    @property
    def price_extended(self):
        if self.price_final and self.quantity:
            return round(Decimal(self.price_final) * self.quantity, 5)
        else:
            return

    def get_absolute_url(self):
        return reverse('transactions:detail-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.item)

transactions/forms.py
from django import forms
from .models import Transaction, TransactionDetail
from django.forms import ModelForm

class TransactionForm(ModelForm):
    class Meta:
        model = Transaction
        fields = '__all__'

class TransactionDetailForm(ModelForm):
    class Meta:
        model = TransactionDetail
        fields = '__all__'

transactions/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone
from django.forms import formset_factory

from .models import Transaction, TransactionDetail
from .forms import TransactionForm, TransactionDetailForm

class TransactionListView(generic.ListView):
    model = Transaction
    template_name = 'transactions/index.html'
    context_object_name = 'transaction_list'

class TransactionDetailView(generic.DetailView):
    model = Transaction
    template_name = 'transactions/detail.html'

    def get_queryset(self):
        queryset = super(TransactionDetailView, self).get_queryset()
        return queryset

#def transaction_detail(request, transaction_id):
#    try:
#        p = Transaction.objects.get(pk=transaction_id)
#    except Transaction.DoesNotExist:
#        raise Http404("Transaction does not exist")
#    return render(request, 'transactions/detail.html', {'transaction': p})

def manage_transactions(request):
    TransactionFormSet = formset_factory(TransactionForm, extra=1, max_num=20)
#    transaction_instance = Transaction.objects.get(id=15)
#    transaction_loaded = {'id': transaction_instance.id, 'date': transaction_instance.date}
    if request.method == 'POST':
        formset = TransactionFormSet(request.POST, request.FILES)
        if formset.is_valid():
            pass
    else:
        formset = TransactionFormSet()
    return render(request, 'transactions/manage.html', {'formset': formset})

class TransactionUpdateView(generic.UpdateView):
    model = Transaction
    form_class = TransactionForm
    template_name = 'transactions/edit.html'

class TransactionDetailListView(generic.ListView):
    model = TransactionDetail
    template_name = 'transactions/detail_index.html'
    context_object_name = 'transaction_detail_list'

class TransactionDetailDetailView(generic.DetailView):
    model = TransactionDetail
    template_name = 'transactions/detail_detail.html'

class TransactionDetailUpdateView(generic.UpdateView):
    model = TransactionDetail
    form_class = TransactionDetailForm
    template_name = 'transactions/detail_edit.html'

def create_transaction(request):
    if request.method =='POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/transactions/')
    else:
        form = TransactionForm()
        return render(request, "transactions/create.html", {'form': form})

def create_transaction_detail(request):
    if request.method =='POST':
        form = TransactionDetailForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/transactions/detail/')
    else:
        form = TransactionDetailForm()
        return render(request, "transactions/detail_create.html", {'form': form})

transactions/templates/transactions/create.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'transactions/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

transactions/templates/transactions/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'transactions/style.css' %}" />
<table>
<tr><td>Date:</td><td>{{ object.date }}</td></tr>
<tr><td>Custom Total:</td><td>{{ object.total_custom }}</td></tr>
<tr><td>Custom Tax Total:</td><td>{{ object.tax_total_custom }}</td></tr>
<tr><td>Tip Total:</td><td>{{ object.tip_total }}</td></tr>
<tr><td>Bags Total:</td><td>{{ object.bags_total }}</td></tr>
<tr><td>Donation Total:</td><td>{{ object.donation_total }}</td></tr>
<tr><td>Custom Grand Total:</td><td>{{ object.grand_total_custom }}</td></tr>
<tr><td>Custom Contact:</td><td>{{ object.contact_custom }}</td></tr>
<tr><td>From Account:</td><td>{{ object.account_from }}</td></tr>
<tr><td>To Account:</td><td>{{ object.account_to }}</td></tr>
<tr><td>Location:</td><td>{{ object.address }}</td></tr>
<tr><td>Total from Transaction Detail:</td><td></td></tr>
</table>

<div>
  <span><a href="edit/">Edit</a></span>
  <span><a href="../">Back</a></span>
</div>

transactions/templates/transactions/detail_create.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'transactions/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

transactions/templates/transactions/detail_detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'transactions/style.css' %}" />
<table>
<tr><td>id:</td><td>{{ object.id }}</td></tr>
<tr><td>Quantity:</td><td>{{ object.quantity }}</td></tr>
<tr><td>Custom Regular Price:</td><td>{{ object.price_regular_custom }}</td></tr>
<tr><td>Custom Discount:</td><td>{{ object.discount_custom }}</td></tr>
<tr><td>Custom Discounted Price:</td><td>{{ object.price_discounted_custom }}</td></tr>
<tr><td>Custom Extended Price:</td><td>{{ object.price_extended_custom }}</td></tr>
<tr><td>Custom CRV Per:</td><td>{{ object.crv_per_custom }}</td></tr>
<tr><td>Custom Tax Per:</td><td>{{ object.tax_per_custom }}</td></tr>
<tr><td>Transaction:</td><td>{{ object.transaction }}</td></tr>
<tr><td>Item:</td><td>{{ object.item }}</td></tr>
<tr><td>Generic Item:</td><td>{{ object.generic_item }}</td></tr>
<tr><td>Custom Base Unit:</td><td>{{ object.custom_base_unit }}</td></tr>
<tr><td>Custom Unit Factor:</td><td>{{ object.custom_unit_factor }}</td></tr>
<tr><td>Calc Discounted Price:</td><td>{{ object.price_discounted_calculated }}</td></tr>
<tr><td>Calc Discount:</td><td>{{ object.discount_calculated }}</td></tr>
<tr><td>Calc Regular Price:</td><td>{{ object.price_regular_calculated }}</td></tr>
<tr><td>Final Price:</td><td>{{ object.price_final }}</td></tr>
<tr><td>Extended Price:</td><td>{{ object.price_extended }}</td></tr>
</table>

<div>
  <span><a href="edit/">Edit</a></span>
  <span><a href="../">Back</a></span>
</div>

transactions/templates/transactions/detail_edit.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'transactions/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

transactions/templates/transactions/detail_index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'transactions/style.css' %}" />

{% if transaction_detail_list %}
  <ul>
    {% for transactiondetail in transaction_detail_list %}
    <li><a href="{% url 'transactions:detail-detail' transactiondetail.id %}">{{ transactiondetail.id }} - {{ transactiondetail.date }} - {{ transactiondetail.item }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No transaction details are available.</p>
{% endif %}
<p><a href="{% url 'transactions:detail-create' %}">Add a transaction detail</a></p>

<div>
  <span><a href="../">Back</a></span>
</div>

transactions/templates/transactions/edit.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'transactions/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

transactions/templates/transactions/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'transactions/style.css' %}" />

{% if transaction_list %}
  <ul>
    {% for transaction in transaction_list %}
    <li><a href="{% url 'transactions:detail' transaction.id %}">{{ transaction.date }} - {{ transaction.address }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No transactions are available.</p>
{% endif %}
<p><a href="{% url 'transactions:create' %}">Add a transaction</a></p>

<div>
  <span><a href="../">Back</a></span>
</div>

transactions/templates/transactions/manage.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'transactions/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  <table>
    {{ formset.as_table }}
  </table>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>