budget/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from budget.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('units/', include('units.urls')),
    path('contacts/', include('contacts.urls')),
    path('items/', include('items.urls')),
    path('transactions/', include('transactions.urls')),
    path('accounts/', include('accounts.urls')),
    path('brands/', include('brands.urls')),
    path('', IndexView.as_view(), name="home"),
]

items/urls.py
from django.urls import path

from . import views

app_name = 'items'
urlpatterns = [
    path('', views.ItemListView.as_view(), name='index'),
    path('<int:pk>/', views.ItemDetailView.as_view(), name='detail'),
    path('create/', views.create_item, name='create'),
    path('<int:pk>/edit/', views.ItemUpdateView.as_view(), name='edit'),
    path('generic/', views.GenericItemListView.as_view(), name='generic-index'),
    path('generic/<int:pk>/', views.GenericItemDetailView.as_view(), name='generic-detail'),
    path('generic/create/', views.create_generic_item, name='generic-create'),
    path('generic/<int:pk>/edit/', views.GenericItemUpdateView.as_view(), name='generic-edit'),
]

items/models.py
from django.db import models
from django.urls import reverse

class GenericItem(models.Model):
    name = models.CharField('Item', max_length=255, blank=True)
    unit = models.ForeignKey('units.Unit', null=True, on_delete=models.SET_NULL)
    base_unit_custom = models.ForeignKey('units.Unit', null=True, on_delete=models.SET_NULL, related_name='genericitem_as_base_unit_custom_set', verbose_name="custom base unit")
    unit_factor_custom = models.DecimalField('Custom Unit Factor', max_digits=10, decimal_places=5, default=1)

    def get_absolute_url(self):
        return reverse('items:generic-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

class Item(models.Model):
    upc = models.CharField('UPC Code', max_length=255, blank=True)
    model_number = models.CharField('Model/Item Number', max_length=255, blank=True)
    description = models.CharField('Description', max_length=255, blank=True)
    milliliters_custom = models.DecimalField('Custom Milliliters', max_digits=10, decimal_places=5, blank=True, null=True)
    unit_factor_custom = models.DecimalField('Custom Unit Factor', max_digits=10, decimal_places=5, blank=True, null=True)
    generic_item = models.ForeignKey('GenericItem', blank=True, null=True, on_delete=models.SET_NULL, verbose_name="generic item", related_name='item_as_generic_item_set')
    unit = models.ForeignKey('units.Unit', null=True, on_delete=models.SET_NULL, related_name='item_as_unit_set', verbose_name="unit")
    base_unit_custom = models.ForeignKey('units.Unit', blank=True, null=True, on_delete=models.SET_NULL, related_name='item_as_base_unit_custom_set', verbose_name="custom base unit")
    brand = models.ForeignKey('brands.Brand', blank=True, null=True, on_delete=models.SET_NULL, related_name='item_as_brand_set')

#    def unit_factor(self):
#        return self.qty_test * self.unit.quantity_per

    def get_absolute_url(self):
        return reverse('items:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.description

items/forms.py
from django import forms
from .models import Item, GenericItem
from django.forms import ModelForm

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

class GenericItemForm(ModelForm):
    class Meta:
        model = GenericItem
        fields = '__all__'

items/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone

from .models import Item, GenericItem
from .forms import ItemForm, GenericItemForm

class ItemListView(generic.ListView):
    model = Item
    template_name = 'items/index.html'
    context_object_name = 'item_list'

class ItemDetailView(generic.DetailView):
    model = Item
    template_name = 'items/detail.html'

class ItemUpdateView(generic.UpdateView):
    model = Item
    form_class = ItemForm
    template_name = 'items/edit.html'

class GenericItemListView(generic.ListView):
    model = GenericItem
    template_name = 'items/generic_index.html'
    context_object_name = 'generic_item_list'

class GenericItemDetailView(generic.DetailView):
    model = GenericItem
    template_name = 'items/generic_detail.html'

class GenericItemUpdateView(generic.UpdateView):
    model = GenericItem
    form_class = GenericItemForm
    template_name = 'items/generic_edit.html'

def create_item(request):
    if request.method =='POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/items/')
    else:
        form = ItemForm()
        return render(request, "items/create.html", {'form': form})

def create_generic_item(request):
    if request.method =='POST':
        form = GenericItemForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/items/generic/')
    else:
        form = GenericItemForm()
        return render(request, "items/generic_create.html", {'form': form})

items/templates/items/create.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'items/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

items/templates/items/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'items/style.css' %}" />
<table>
  <tr><td>Brand:</td><td>{{ object.brand }}</td></tr>
  <tr><td>UPC:</td><td>{{ object.upc }}</td></tr>
  <tr><td>Model Number:</td><td>{{ object.model_number }}</td></tr>
  <tr><td>Description:</td><td>{{ object.description }}</td></tr>
  <tr><td>Custom ml:</td><td>{{ object.milliliters_custom }}</td></tr>
  <tr><td>Custom Unit Factor:</td><td>{{ object.unit_factor_custom }}</td></tr>
  <tr><td>Generic Item:</td><td>{{ object.generic_item }}</td></tr>
  <tr><td>Unit:</td><td>{{ object.unit }}</td></tr>
  <tr><td>Custom Unit:</td><td>{{ object.base_unit_custom }}</td></tr>
</table>

<div>
  <span><a href="edit/">Edit</a></span>
  <span><a href="../">Back</a></span>
</div>

items/templates/items/edit.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'items/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

items/templates/items/generic_create.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'items/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

items/templates/items/generic_detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'items/style.css' %}" />
<table>
  <tr><td>Name:</td><td>{{ object.name }}</td></tr>
  <tr><td>Unit:</td><td>{{ object.unit }}</td></tr>
  <tr><td>Custom Base Unit:</td><td>{{ object.base_unit_custom }}</td></tr>
  <tr><td>Custom Unit Factor:</td><td>{{ object.unit_factor_custom }}</td></tr>
</table>

<div>
  <span><a href="edit/">Edit</a></span>
  <span><a href="../">Back</a></span>
</div>

items/templates/items/generic_edit.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'items/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

items/templates/items/generic_index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'items/style.css' %}" />

{% if generic_item_list %}
  <ul>
    {% for genericitem in generic_item_list %}
    <li><a href="{% url 'items:generic-detail' genericitem.id %}">{{ genericitem.description }} - {{ genericitem.unit }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No generic items are available.</p>
{% endif %}
<p><a href="{% url 'items:generic-create' %}">Add a generic item</a></p>

<div>
  <span><a href="../">Back</a></span>
</div>

items/templates/items/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'items/style.css' %}" />

{% if item_list %}
  <ul>
    {% for item in item_list %}
    <li><a href="{% url 'items:detail' item.id %}">{{ item.description }} - {{ item.unit }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No items are available.</p>
{% endif %}
<p><a href="{% url 'items:create' %}">Add an item</a></p>

<div>
  <span><a href="../">Back</a></span>
</div>