accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.AccountListView.as_view(), name='index'),
    path('<int:pk>/', views.AccountDetailView.as_view(), name='detail'),
    path('create/', views.create_account, name='create'),
    path('<int:pk>/edit/', views.AccountUpdateView.as_view(), name='edit'),
]

budget/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from budget.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('units/', include('units.urls')),
    path('contacts/', include('contacts.urls')),
    path('items/', include('items.urls')),
    path('transactions/', include('transactions.urls')),
    path('accounts/', include('accounts.urls')),
    path('brands/', include('brands.urls')),
    path('', IndexView.as_view(), name="home"),
]

items/urls.py
from django.urls import path

from . import views

app_name = 'items'
urlpatterns = [
    path('', views.ItemListView.as_view(), name='index'),
    path('<int:pk>/', views.ItemDetailView.as_view(), name='detail'),
    path('create/', views.create_item, name='create'),
    path('<int:pk>/edit/', views.ItemUpdateView.as_view(), name='edit'),
    path('generic/', views.GenericItemListView.as_view(), name='generic-index'),
    path('generic/<int:pk>/', views.GenericItemDetailView.as_view(), name='generic-detail'),
    path('generic/create/', views.create_generic_item, name='generic-create'),
    path('generic/<int:pk>/edit/', views.GenericItemUpdateView.as_view(), name='generic-edit'),
]

accounts/models.py
from django.db import models
from django.urls import reverse

class Account(models.Model):
    name = models.CharField('Account Name', max_length=255, blank=True)
    account_number = models.CharField('Account Number', max_length=255, blank=True)
    card_number_last4 = models.CharField('Card Number (last 4 digits)', max_length=255, blank=True)

    def get_absolute_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.pk})

    def __str__(self):
        if self.card_number_last4:
            return '%s (%s)' % (self.name, self.card_number_last4)
        else:
            return self.name

accounts/forms.py
from django import forms
from .models import Account
from django.forms import ModelForm

class AccountForm(ModelForm):
    class Meta:
        model = Account
        fields = '__all__'

accounts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone

from .models import Account
from .forms import AccountForm

class AccountListView(generic.ListView):
    model = Account
    template_name = 'accounts/index.html'
    context_object_name = 'account_list'

class AccountDetailView(generic.DetailView):
    model = Account
    template_name = 'accounts/detail.html'

class AccountUpdateView(generic.UpdateView):
    model = Account
    form_class = AccountForm
    template_name = 'accounts/edit.html'

def create_account(request):
    if request.method =='POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/accounts/')
    else:
        form = AccountForm()
        return render(request, "accounts/create.html", {'form': form})

accounts/templates/accounts/address_create.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

accounts/templates/accounts/address_detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />
<table>
  <tr><td>Name:</td><td>{{ object.name }}</td></tr>
</table>

<div>
  <span><a href="edit/">Edit</a></span>
  <span><a href="../">Back</a></span>
</div>

accounts/templates/accounts/create.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

accounts/templates/accounts/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />
<table>
  <tr><td>Name:</td><td>{{ object.name }}</td></tr>
  <tr><td>Account Number:</td><td>{{ object.account_number }}</td></tr>
  <tr><td>Card Number (last 4):</td><td>{{ object.card_number_last4 }}</td></tr>
</table>

<div>
  <span><a href="edit/">Edit</a></span>
  <span><a href="../">Back</a></span>
</div>

accounts/templates/accounts/edit.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

accounts/templates/accounts/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />

{% if account_list %}
  <ul>
    {% for account in account_list %}
    <li><a href="{% url 'accounts:detail' account.id %}">{{ account.name }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No accounts are available.</p>
{% endif %}
<p><a href="{% url 'accounts:create' %}">Add an account</a></p>

<div>
  <span><a href="../">Back</a></span>
</div>