budget/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from budget.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('units/', include('units.urls')),
    path('contacts/', include('contacts.urls')),
    path('items/', include('items.urls')),
    path('transactions/', include('transactions.urls')),
    path('accounts/', include('accounts.urls')),
    path('brands/', include('brands.urls')),
    path('', IndexView.as_view(), name="home"),
]

contacts/urls.py
from django.urls import path

from . import views

app_name = 'contacts'
urlpatterns = [
    path('', views.ContactListView.as_view(), name='index'),
    path('<int:pk>/', views.ContactDetailView.as_view(), name='detail'),
    path('create/', views.create_contact, name='create'),
    path('<int:pk>/edit/', views.ContactUpdateView.as_view(), name='edit'),
    path('address/', views.AddressListView.as_view(), name='address-index'),
    path('address/<int:pk>/', views.AddressDetailView.as_view(), name='address-detail'),
    path('address/create/', views.create_address, name='address-create'),
    path('address/<int:pk>/edit/', views.AddressUpdateView.as_view(), name='address-edit'),
]

items/urls.py
from django.urls import path

from . import views

app_name = 'items'
urlpatterns = [
    path('', views.ItemListView.as_view(), name='index'),
    path('<int:pk>/', views.ItemDetailView.as_view(), name='detail'),
    path('create/', views.create_item, name='create'),
    path('<int:pk>/edit/', views.ItemUpdateView.as_view(), name='edit'),
    path('generic/', views.GenericItemListView.as_view(), name='generic-index'),
    path('generic/<int:pk>/', views.GenericItemDetailView.as_view(), name='generic-detail'),
    path('generic/create/', views.create_generic_item, name='generic-create'),
    path('generic/<int:pk>/edit/', views.GenericItemUpdateView.as_view(), name='generic-edit'),
]

contacts/models.py
from django.db import models
from django.urls import reverse

class Contact(models.Model):
    name = models.CharField('Contact', max_length=255)
#    testfield = models.CharField('test', max_length=255, default="test")

    def get_absolute_url(self):
        return reverse('contacts:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

class Address(models.Model):
    street_number = models.CharField('Street Number', max_length=255, blank=True)
    street_cardinal = models.CharField('Street Cardinal', max_length=255, blank=True)
    street_name = models.CharField('Street Name', max_length=255, null=True, blank=True)
    street_class = models.CharField('Street Class', max_length=255, blank=True)
    city = models.CharField('City', max_length=255, blank=True)
    state = models.CharField('State', max_length=255, blank=True)
    zip_code = models.CharField('Zip Code', max_length=255, blank=True)
    phone_number = models.CharField('Phone Number', max_length=255, blank=True)
    contact = models.ForeignKey('Contact', null=True, on_delete=models.SET_NULL, related_name='address_as_contact_set', verbose_name="contact")

    def get_absolute_url(self):
        return reverse('contacts:address-detail', kwargs={'pk': self.pk})

#    @property
#    def testfield(self):
#        return self.contact.testfield

    def __str__(self):
        return '%s - %s %s %s %s - %s' % (self.contact, self.street_number, self.street_cardinal, self.street_name, self.street_class, self.city)

    class Meta:
        verbose_name_plural = "addresses"

contacts/forms.py
from django import forms
from .models import Contact, Address
from django.forms import ModelForm

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

class AddressForm(ModelForm):
    class Meta:
        model = Address
        fields = '__all__'

contacts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone

from .models import Contact, Address
from .forms import ContactForm, AddressForm

class ContactListView(generic.ListView):
    model = Contact
    template_name = 'contacts/index.html'
    context_object_name = 'contact_list'

class ContactDetailView(generic.DetailView):
    model = Contact
    template_name = 'contacts/detail.html'

class ContactUpdateView(generic.UpdateView):
    model = Contact
    form_class = ContactForm
    template_name = 'contacts/edit.html'

class AddressListView(generic.ListView):
    model = Address
    template_name = 'contacts/address_index.html'
    context_object_name = 'address_list'

class AddressDetailView(generic.DetailView):
    model = Address
    template_name = 'contacts/address_detail.html'

class AddressUpdateView(generic.UpdateView):
    model = Address
    form_class = AddressForm
    template_name = 'contacts/address_edit.html'

def create_contact(request):
    if request.method =='POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/contacts/')
    else:
        form = ContactForm()
        return render(request, "contacts/create.html", {'form': form})

def create_address(request):
    if request.method =='POST':
        form = AddressForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/contacts/address/')
    else:
        form = AddressForm()
        return render(request, "contacts/address_create.html", {'form': form})

contacts/templates/contacts/address_create.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'contacts/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

contacts/templates/contacts/address_detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'contacts/style.css' %}" />
<table>
  <tr><td>Name:</td><td>{{ object.name }}</td></tr>
  <tr><td>Street Number:</td><td>{{ object.street_number }}</td></tr>
  <tr><td>Street Cardinal:</td><td>{{ object.street_cardinal }}</td></tr>
  <tr><td>Street Name:</td><td>{{ object.street_name }}</td></tr>
  <tr><td>Street Class:</td><td>{{ object.street_class }}</td></tr>
  <tr><td>City:</td><td>{{ object.city }}</td></tr>
  <tr><td>State:</td><td>{{ object.state }}</td></tr>
  <tr><td>Zip Code:</td><td>{{ object.zip_code }}</td></tr>
  <tr><td>Phone Number:</td><td>{{ object.phone_number }}</td></tr>
  <tr><td>Contact:</td><td>{{ object.contact }}</td></tr>
</table>

<div>
  <span><a href="edit/">Edit</a></span>
  <span><a href="../">Back</a></span>
</div>

contacts/templates/contacts/address_edit.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'contacts/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

contacts/templates/contacts/address_index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'contacts/style.css' %}" />

{% if address_list %}
  <ul>
    {% for address in address_list %}
    <li><a href="{% url 'contacts:address-detail' address.id %}">{{ address.street_name }} - {{ address.city }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No addresses are available.</p>
{% endif %}
<p><a href="{% url 'contacts:address-create' %}">Add an address</a></p>

<div>
  <span><a href="../">Back</a></span>
</div>

contacts/templates/contacts/create.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'contacts/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

contacts/templates/contacts/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'contacts/style.css' %}" />
<table>
  <tr><td>Name:</td><td>{{ object.name }}</td></tr>
</table>

<div>
  <span><a href="edit/">Edit</a></span>
  <span><a href="../">Back</a></span>
</div>

contacts/templates/contacts/edit.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'contacts/style.css' %}" />

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<div>
  <span><a href="../">Back</a></span>
</div>

contacts/templates/contacts/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'contacts/style.css' %}" />

{% if contact_list %}
  <ul>
    {% for contact in contact_list %}
    <li><a href="{% url 'contacts:detail' contact.id %}">{{ contact.name }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No contacts are available.</p>
{% endif %}
<p><a href="{% url 'contacts:create' %}">Add a contact</a></p>

<div>
  <span><a href="../">Back</a></span>
</div>